version: "3"

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: always
    ports:
      - 5050:80

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - ADDRESS=0.0.0.0:8080
      - POSTGRES_CONN=postgresql://user:password@postgres:5432/db
      - JWTKEY=helloworld
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: always
    ports:
      - 8080:8080


volumes:
  pg_data:
  pgadmin_data:
